version: '3.8'

services:
  # 导航站应用服务（连接到远程 MySQL）
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navigation-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://gemini:123.abc@192.168.8.219:3308/gemini
      - ADMIN_PASSWORD=chenbang198859
      - UPLOAD_DIR=uploads
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/public/uploads
      - logs_data:/app/logs
    networks:
      - navigation-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: navigation-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/standalone.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads_data:/var/www/uploads:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - navigation-network
    profiles:
      - nginx

# 数据卷
volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local

# 网络
networks:
  navigation-network:
    driver: bridge